---
title: "Supplementary analyses"
output: html_notebook
---

## Scaled vs. unscaled ODBA

```{r Summarise scaling factors}
# scaling_factors <- read.csv(here("outputs","calibration-outputs","tag_6O_scaling_factors.csv"))
# scaling_factors <- scaling_factors %>%
#   pivot_longer(cols=c("x_scaling_factor","y_scaling_factor","z_scaling_factor"),
#                       names_to = "axis")
# options(digits=3)
# min(scaling_factors$value)
# max(scaling_factors$value)
# mean(scaling_factors$value)
# sd(scaling_factors$value)
```

```{r Import and group ODBA}
# odba_path <- "../outputs/windowed-odba/unlabelled-full-dataset/10min-odba/"
# odba_files <- paste0(odba_path, list.files(odba_path))
# odba <- bind_rows(lapply(odba_files, fread, 
#                          colClasses=c("tag_ID" = "character", 
#                                       "start_dt_utc"="character",
#                                       "end_dt_utc"="character")))
# ind_odba <- odba %>%
#   group_by(tag_ID) %>%
#   summarise(mean_unscaled_odba=mean(mean_ODBA, na.rm=T),
#             mean_scaled_odba=mean(mean_60_scaled_ODBA, na.rm=T),
#             n_windows=n()) %>%
#   filter(!is.na(mean_scaled_odba))
# 
# ind_odba %>%
#   arrange(mean_unscaled_odba) %>%
#   flextable()
```

```{r Calculate correlation and plot}
# scaling_cor = cor.test(ind_odba$mean_scaled_odba, ind_odba$mean_unscaled_odba, method="spearman")
# 
# scaling_cor_plot <- ggplot(ind_odba, aes(x=mean_scaled_odba, y=mean_unscaled_odba)) +
#   geom_point(size=small.point.size)+
#   theme_classic()+
#   xlab("\ncalibrated mean ODBA") +
#   ylab("mean ODBA without calibration\n") +
#   geom_text(x = 0.04, y=0.55, 
#             hjust=0, 
#             label=expression(r["s"]*" = 0.9998"),
#             family=font.family,
#             size=(axis.heading.size+1) / (14/5))+
#   theme(text=element_text(family=font.family),
#         axis.text = element_text(size=label.size),
#         axis.title = element_text(size=axis.heading.size),
#         plot.title = element_text(size=axis.heading.size+2))
# 
# scaling_cor_plot
```

```{r}
# if(save_plots==TRUE){
# ggsave(plot=scaling_cor_plot,
#        filename='figure-scaling-correlation.jpg',
#        path=output_path,
#        width=16,
#        height=10,
#        units="cm",
#        dpi=300)
# }
```

